services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: afisha_db
      PG_DATA: /var/lib/postgresql/data/
    ports:
      - 5417:5432
    volumes:
      - db:/var/lib/postgresql/data/
volumes:
  db: